name: Daily Dev Bookmarks

on:
  workflow_run:
    workflows: ["Setup Actions"]
    types:
      - completed
  repository_dispatch:
    types:
      - dailydev
  workflow_dispatch:

jobs:
  dailydev:
    name: Updated Bookmarks of daily.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_KBASE }}

      - name: Update Bookmarks
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DAILYDEV-BOOKMARKS"
          feed_list: "https://api.daily.dev/rss/b/1c145acc-b14f-4f40-b08f-976534d3bf82"
          max_post_count: 20
          readme_path: "./bookmarks.md"
          gh_token: ${{ secrets.GH_KBASE }}
          commit_message: "Updated bookmarks from daily.dev"
          committer_username: "iamsarvagyaa"
          committer_email: ${{ secrets.GH_EMAIL }}
          enable_keepalive: true
          retry_count: 6
          retry_wait_time: 10

      - name: Github event failure
        if: ${{ !github.event.client_payload.passed }}
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE

      - name: Finished
        run: echo "Workflow execution completed successfully."
  
      